In [1]:
import pandas as pd
import numpy as np

In [2]:
data = pd.read_csv('vertebrate.csv')

In [3]:
data

Name Body Temperature Skin Cover Gives Birth Aquatic Creature  \
0           human     warm-blooded       hair         yes               no   
1          python     cold-blooded     scales          no               no   
2          salmon     cold-blooded     scales          no              yes   
3           whale     warm-blooded       hair         yes              yes   
4            frog     cold-blooded       none          no             semi   
5   komodo dragon     cold-blooded     scales          no               no   
6             bat     warm-blooded       hair         yes               no   
7          pigeon     warm-blooded   feathers          no               no   
8             cat     warm-blooded        fur         yes               no   
9   leopard shark     cold-blooded     scales         yes              yes   
10         turtle     cold-blooded     scales          no             semi   
11        penguin     warm-blooded   feathers          no             semi   
12      porcupine     warm-blooded     quills         yes               no   
13            eel     cold-blooded     scales          no              yes   
14     salamander     cold-blooded       none          no             semi   
15   gila monster     cold-blooded     scales          no               no   

   Aerial Creature Has Legs Hibernates Class Label  
0               no      yes         no      mammal  
1               no       no        yes     reptile  
2               no       no         no        fish  
3               no       no         no      mammal  
4               no      yes        yes   amphibian  
5               no      yes         no     reptile  
6              yes      yes        yes      mammal  
7              yes      yes         no        bird  
8               no      yes         no      mammal  
9               no       no         no        fish  
10              no      yes         no     reptile  
11              no      yes         no        bird  
12              no      yes        yes      mammal  
13              no       no         no        fish  
14              no      yes        yes   amphibian  
15              no      yes        yes         NaN

In [4]:
X_data = data.iloc[:,:-1]

In [5]:
X_data

Name Body Temperature Skin Cover Gives Birth Aquatic Creature  \
0           human     warm-blooded       hair         yes               no   
1          python     cold-blooded     scales          no               no   
2          salmon     cold-blooded     scales          no              yes   
3           whale     warm-blooded       hair         yes              yes   
4            frog     cold-blooded       none          no             semi   
5   komodo dragon     cold-blooded     scales          no               no   
6             bat     warm-blooded       hair         yes               no   
7          pigeon     warm-blooded   feathers          no               no   
8             cat     warm-blooded        fur         yes               no   
9   leopard shark     cold-blooded     scales         yes              yes   
10         turtle     cold-blooded     scales          no             semi   
11        penguin     warm-blooded   feathers          no             semi   
12      porcupine     warm-blooded     quills         yes               no   
13            eel     cold-blooded     scales          no              yes   
14     salamander     cold-blooded       none          no             semi   
15   gila monster     cold-blooded     scales          no               no   

   Aerial Creature Has Legs Hibernates  
0               no      yes         no  
1               no       no        yes  
2               no       no         no  
3               no       no         no  
4               no      yes        yes  
5               no      yes         no  
6              yes      yes        yes  
7              yes      yes         no  
8               no      yes         no  
9               no       no         no  
10              no      yes         no  
11              no      yes         no  
12              no      yes        yes  
13              no       no         no  
14              no      yes        yes  
15              no      yes        yes

In [6]:
y_train = data['Class Label'][:-1]

In [7]:
y_train.values

array(['mammal', 'reptile', 'fish', 'mammal', 'amphibian', 'reptile',
       'mammal', 'bird', 'mammal', 'fish', 'reptile', 'bird', 'mammal',
       'fish', 'amphibian'], dtype=object)

In [8]:
from sklearn.feature_extraction import DictVectorizer

X_dict = X_data.T.to_dict().values()

In [9]:
X_dict

[{'Aerial Creature': 'no',
  'Aquatic Creature': 'no',
  'Body Temperature': 'warm-blooded',
  'Gives Birth': 'yes',
  'Has Legs': 'yes',
  'Hibernates': 'no',
  'Name': 'human',
  'Skin Cover': 'hair'},
 {'Aerial Creature': 'no',
  'Aquatic Creature': 'no',
  'Body Temperature': 'cold-blooded',
  'Gives Birth': 'no',
  'Has Legs': 'no',
  'Hibernates': 'yes',
  'Name': 'python',
  'Skin Cover': 'scales'},
 {'Aerial Creature': 'no',
  'Aquatic Creature': 'yes',
  'Body Temperature': 'cold-blooded',
  'Gives Birth': 'no',
  'Has Legs': 'no',
  'Hibernates': 'no',
  'Name': 'salmon',
  'Skin Cover': 'scales'},
 {'Aerial Creature': 'no',
  'Aquatic Creature': 'yes',
  'Body Temperature': 'warm-blooded',
  'Gives Birth': 'yes',
  'Has Legs': 'no',
  'Hibernates': 'no',
  'Name': 'whale',
  'Skin Cover': 'hair'},
 {'Aerial Creature': 'no',
  'Aquatic Creature': 'semi',
  'Body Temperature': 'cold-blooded',
  'Gives Birth': 'no',
  'Has Legs': 'yes',
  'Hibernates': 'yes',
  'Name': 'frog',


In [10]:
vect = DictVectorizer(sparse=False)
X_vector = vect.fit_transform(X_dict)

In [11]:
X_vector

array([[ 1.,  0.,  1.,  0.,  0.,  0.,  1.,  0.,  1.,  0.,  1.,  1.,  0.,
         0.,  0.,  0.,  0.,  0.,  1.,  0.,  0.,  0.,  0.,  0.,  0.,  0.,
         0.,  0.,  0.,  0.,  0.,  1.,  0.,  0.,  0.],
       [ 1.,  0.,  1.,  0.,  0.,  1.,  0.,  1.,  0.,  1.,  0.,  0.,  1.,
         0.,  0.,  0.,  0.,  0.,  0.,  0.,  0.,  0.,  0.,  0.,  1.,  0.,
         0.,  0.,  0.,  0.,  0.,  0.,  0.,  0.,  1.],
       [ 1.,  0.,  0.,  0.,  1.,  1.,  0.,  1.,  0.,  1.,  0.,  1.,  0.,
         0.,  0.,  0.,  0.,  0.,  0.,  0.,  0.,  0.,  0.,  0.,  0.,  0.,
         1.,  0.,  0.,  0.,  0.,  0.,  0.,  0.,  1.],
       [ 1.,  0.,  0.,  0.,  1.,  0.,  1.,  0.,  1.,  1.,  0.,  1.,  0.,
         0.,  0.,  0.,  0.,  0.,  0.,  0.,  0.,  0.,  0.,  0.,  0.,  0.,
         0.,  0.,  1.,  0.,  0.,  1.,  0.,  0.,  0.],
       [ 1.,  0.,  0.,  1.,  0.,  1.,  0.,  1.,  0.,  0.,  1.,  0.,  1.,
         0.,  0.,  0.,  1.,  0.,  0.,  0.,  0.,  0.,  0.,  0.,  0.,  0.,
         0.,  0.,  0.,  0.,  0.,  0.,  1.,  0.,  0.],


In [12]:
vect

DictVectorizer(dtype=<type 'numpy.float64'>, separator='=', sort=True,
        sparse=False)

In [13]:
# 0 to 14 is train set
X_train = X_vector[:-1]
# 15th is test set
X_test = X_vector[-1:] 

In [14]:
from sklearn.preprocessing import LabelEncoder

# Used to vectorize the class label
le = LabelEncoder()
y_train = le.fit_transform(y_train)

In [15]:
y_train

array([3, 4, 2, 3, 0, 4, 3, 1, 3, 2, 4, 1, 3, 2, 0])

In [16]:
from sklearn import tree

clf = tree.DecisionTreeClassifier(criterion='entropy')
clf = clf.fit(X_train,y_train)

In [17]:
# Predict the test data, not seen earlier
le.inverse_transform(clf.predict(X_test))

array(['reptile'], dtype=object)

In [18]:
clf.predict(X_test)

array([4])

In [19]:
le

LabelEncoder()

In [21]:
# prediction with the same training set
Train_predict = clf.predict(X_train)

In [22]:
# Metrics related to the DecisionTreeClassifier
from sklearn.metrics import accuracy_score, classification_report

print 'Accuracy is:', accuracy_score(y_train, Train_predict)
print classification_report(y_train, Train_predict)

Accuracy is: 1.0
             precision    recall  f1-score   support

          0       1.00      1.00      1.00         2
          1       1.00      1.00      1.00         2
          2       1.00      1.00      1.00         3
          3       1.00      1.00      1.00         5
          4       1.00      1.00      1.00         3

avg / total       1.00      1.00      1.00        15

